spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: springbootmybatis
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    mysql:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      filters: stat,wall,log4j
      maxActive: 20
      initialSize: 5
      maxWait: 60000
      minIdle: 5
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      logSlowSql: true
  encoding:
      charset: UTF-8
      enabled: true
      # force是将request和response都设置字符集
      force: true
    # redis默认配置
  redis:
    database: 0
    host: localhost
    port: 6379

  #邮箱配置
  mail:
    host: smtp.qq.com
    username: 1783461699@qq.com
    #QQ邮箱的授权码
    password: xxxxxxxx
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: 7771
#mybatis配置
mybatis:
  mapperLocations: classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    jdbc-type-for-null: "NULL"
    map-underscore-to-camel-case: true
