spring:
  application:
    name: springbootmybatis
  profiles:
    active: dev
  encoding:
      charset: UTF-8
      enabled: true
      # force是将request和response都设置字符集
      force: true
    # redis默认配置
  redis:
    database: 0
    host: localhost
    port: 6379

  #邮箱配置
  mail:
    host: smtp.qq.com
    username: 1783461699@qq.com
    #QQ邮箱的授权码
    password: xxxxxxxx
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

#mybatis配置
mybatis:
  mapperLocations: classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    jdbc-type-for-null: "NULL"
    map-underscore-to-camel-case: true
